spring.application.name=configserver

server.port=8888

#changing centralrepo to local-file system
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:C://training//centralrepo
